#!/bin/bash
#
# Rsync the cloudapi build in this working copy to the install on the given
# HN. If there are multiple cloudapi instances and/or the instance isn't
# on the HN, this'll fail.
#

if [[ -n "$TRACE" ]]; then
    export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi
set -o errexit
set -o pipefail

TOP=$(cd $(dirname $0)/../; pwd)
NODE=$1

if [[ -z "$CLOUDAPI_ZONE" ]]; then
    CLOUDAPI_ZONE=$(ssh $NODE "/opt/smartdc/bin/sdc-vmapi /vms" 2>/dev/null \
        | json -H -c 'this.tags && this.tags.smartdc_role === "cloudapi"' \
            -c 'this.state === "running"' 0.uuid)
fi
echo "CLOUDAPI_ZONE: $CLOUDAPI_ZONE"

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node --exclude build"
else
    # Clean node_modules everytime.
    ssh $NODE rm -rf /zones/$CLOUDAPI_ZONE/root/opt/smartdc/cloudapi/node_modules
fi

rsync -av ${TOP}/ \
    $NODE:/zones/$CLOUDAPI_ZONE/root/opt/smartdc/cloudapi/ \
    $extraOpts \
    --exclude .git/ \
    --exclude /etc/ \
    --exclude /deps/ \
    --exclude /doc/ \
    --exclude /tools/ \
    --exclude /tmp/

SERVICES=$(ssh ${NODE} svcs -z ${CLOUDAPI_ZONE} -H -o fmri cloudapi)
for service in $SERVICES; do
    state=$(ssh ${NODE} svcs -z ${CLOUDAPI_ZONE} -H -o state $service)
    if [[ "$state" == "maintenance" ]]; then
        ssh ${NODE} svcadm -z ${CLOUDAPI_ZONE} clear $service
    else
        ssh ${NODE} svcadm -z ${CLOUDAPI_ZONE} restart $service
    fi
done
ssh ${NODE} svcadm -z ${CLOUDAPI_ZONE} restart config-agent
